name: nptrs_project_website
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flex_seed_scheme: ^1.2.4
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  material: ^1.0.0+2
  pdfx: ^2.3.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/schedulebuilder_screenshot.png
    - assets/weekly-reports/
    - assets/AllDocuments.zip
    - assets/SoftwareRequirementsSpecification.pdf
    - assets/Week1-16.zip